# aether theme
baseurl = "http://example.org"
title = "Palaver"
author = "Jerad Acosta"
canonifyurls = true
paginate = 5
theme = "aether"

publishDir = "docs"

[params]
brand = "Storytelling"
description = "Creatively Shared Storytelling"
bgimg = "img/ignasi_pattern_s.png"
