# aether theme
baseurl = "http://palaver.jerad.xyz"
title = "Palaver"
author = "Jerad Acosta"
canonifyurls = true
paginate = 5
theme = "aether"
googleanalytics = "UA-144921519-1"
disqusShortname = "irpalaver"

publishDir = "docs"

[params]
brand = "Storytelling"
description = "Creatively Shared Storytelling"
bgimg = "/img/paper/opendoorhills.png"

# [params.posts]
#     folderName = "post"
#     pageSize = "6"
#     featuredPost = "true"
#     paginationPages = 2
#     showFirstLast = false

# [params.posts]
#     folderName = "work"
#     pageSize = "2"
#     featuredPost = "true"
#     paginationPages = 4
#     showFirstLast = true