# aether theme
baseurl = "http://palaver.jerad.xyz"
title = "Palaver"
author = "Jerad Acosta"
canonifyurls = true
paginate = 5
theme = "aether"
googleanalytics = "UA-91420291-1"
disqusShortname = "irJERAD"

publishDir = "docs"

[params]
brand = "Storytelling"
description = "Creatively Shared Storytelling"
bgimg = "img/paper/opendoorhills.png"
